<?xml version="1.0" encoding="utf-8"?><Database Name="ActivEarth_Dev" Class="ActivEarthDataProvidersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=ActivEarth_Dev;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ActivEarth_DevConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.profile" Member="ProfileDataProviders">
    <Type Name="ProfileDataProvider">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ProfileDataProvider_team_member" Member="ContestUserDataProviders" ThisKey="id" OtherKey="user_id" Type="ContestUserDataProvider" />
      <Association Name="UserDataProvider_ProfileDataProvider" Member="UserDataProvider" ThisKey="user_id" OtherKey="id" Type="UserDataProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="UserDataProviders">
    <Type Name="UserDataProvider">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="UserDataProvider_ProfileDataProvider" Member="ProfileDataProviders" ThisKey="id" OtherKey="user_id" Type="ProfileDataProvider" />
    </Type>
  </Table>
  <Table Name="dbo.challenges" Member="ChallengeDataProviders">
    <Type Name="ChallengeDataProvider">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="requirement" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="persistent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="end_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="duration_days" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statistic" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.contests" Member="ContestDataProviders">
    <Type Name="ContestDataProvider">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="end_mode" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="end_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="end_goal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="statistic" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="contest_team" Member="TeamDataProviders" ThisKey="id" OtherKey="contest_id" Type="TeamDataProvider" />
    </Type>
  </Table>
  <Table Name="dbo.team_members" Member="ContestUserDataProviders">
    <Type Name="ContestUserDataProvider">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="team_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="initial_score" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="initialized" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ProfileDataProvider_team_member" Member="ProfileDataProvider" ThisKey="user_id" OtherKey="id" Type="ProfileDataProvider" IsForeignKey="true" />
      <Association Name="team_team_member" Member="TeamDataProvider" ThisKey="team_id" OtherKey="id" Type="TeamDataProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.teams" Member="TeamDataProviders">
    <Type Name="TeamDataProvider">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="contest_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="team_team_member" Member="ContestUserDataProviders" ThisKey="id" OtherKey="team_id" Type="ContestUserDataProvider" />
      <Association Name="contest_team" Member="ContestDataProvider" ThisKey="contest_id" OtherKey="id" Type="ContestDataProvider" IsForeignKey="true" />
    </Type>
  </Table>
</Database>