insert into ActivEarth_Dev.dbo.users Values ('jtest', 'test123')
insert into ActivEarth_Dev.dbo.profile Values (1, 'John', 'Test', 'jtest@gmail.com', 'M', 'Derpville', 'VA', 21, 72, 175)

insert into ActivEarth_Dev.dbo.users Values ('badgetest1', 'password')
insert into ActivEarth_Dev.dbo.profile Values (2, 'Test', 'Subject1', 'thisisatestaccount@email.com', 'M', 'Denver', 'CO', 21, 72, 175)

insert into ActivEarth_Dev.dbo.users Values ('badgetest2', 'password2')
insert into ActivEarth_Dev.dbo.profile Values (3, 'Test', 'Subject2', 'anothertestaccount@email.com', 'M', 'St. Louis', 'MO', 26, 72, 175)

insert into ActivEarth_Dev.dbo.statistic_info Values (0, 'Steps', '{0}')
insert into ActivEarth_Dev.dbo.statistic_info Values (1, 'Distance Walked', '{0:0.0}')
insert into ActivEarth_Dev.dbo.statistic_info Values (2, 'Distance Biked', '{0:0.0}')
insert into ActivEarth_Dev.dbo.statistic_info Values (3, 'Distance Ran', '{0:0.0}')
insert into ActivEarth_Dev.dbo.statistic_info Values (4, 'Gas Money Saved', '${0:0.00}')
insert into ActivEarth_Dev.dbo.statistic_info Values (5, 'Challenges Completed', '{0}')

insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 0, 0, 0, '~/Images/Competition/Badges/Steps/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 1, 30000, 50, '~/Images/Competition/Badges/Steps/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 2, 300000, 100, '~/Images/Competition/Badges/Steps/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 3, 900000, 250, '~/Images/Competition/Badges/Steps/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 4, 1800000, 400, '~/Images/Competition/Badges/Steps/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 5, 2850000, 650, '~/Images/Competition/Badges/Steps/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 6, 4050000, 800, '~/Images/Competition/Badges/Steps/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 7, 5550000, 1050, '~/Images/Competition/Badges/Steps/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 8, 7200000, 1200, '~/Images/Competition/Badges/Steps/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 0, 0, 0, '~/Images/Competition/Badges/Distance_Walked/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 1, 20, 50, '~/Images/Competition/Badges/Distance_Walked/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 2, 150, 100, '~/Images/Competition/Badges/Distance_Walked/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 3, 450, 250, '~/Images/Competition/Badges/Distance_Walked/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 4, 900, 400, '~/Images/Competition/Badges/Distance_Walked/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 5, 1425, 650, '~/Images/Competition/Badges/Distance_Walked/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 6, 2025, 800, '~/Images/Competition/Badges/Distance_Walked/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 7, 2775, 1050, '~/Images/Competition/Badges/Distance_Walked/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 8, 3600, 1200, '~/Images/Competition/Badges/Distance_Walked/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 0, 0, 0, '~/Images/Competition/Badges/Distance_Biked/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 1, 20, 50, '~/Images/Competition/Badges/Distance_Biked/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 2, 150, 100, '~/Images/Competition/Badges/Distance_Biked/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 3, 450, 250, '~/Images/Competition/Badges/Distance_Biked/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 4, 900, 400, '~/Images/Competition/Badges/Distance_Biked/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 5, 1425, 650, '~/Images/Competition/Badges/Distance_Biked/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 6, 2025, 800, '~/Images/Competition/Badges/Distance_Biked/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 7, 2775, 1050, '~/Images/Competition/Badges/Distance_Biked/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 8, 3600, 1200, '~/Images/Competition/Badges/Distance_Biked/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 0, 0, 0, '~/Images/Competition/Badges/Distance_Ran/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 1, 20, 50, '~/Images/Competition/Badges/Distance_Ran/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 2, 150, 100, '~/Images/Competition/Badges/Distance_Ran/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 3, 450, 250, '~/Images/Competition/Badges/Distance_Ran/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 4, 900, 400, '~/Images/Competition/Badges/Distance_Ran/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 5, 1425, 650, '~/Images/Competition/Badges/Distance_Ran/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 6, 2025, 800, '~/Images/Competition/Badges/Distance_Ran/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 7, 2775, 1050, '~/Images/Competition/Badges/Distance_Ran/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 8, 3600, 1200, '~/Images/Competition/Badges/Distance_Ran/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 0, 0, 0, '~/Images/Competition/Badges/Gas_Savings/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 1, 10, 50, '~/Images/Competition/Badges/Gas_Savings/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 2, 20, 100, '~/Images/Competition/Badges/Gas_Savings/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 3, 40, 250, '~/Images/Competition/Badges/Gas_Savings/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 4, 60, 400, '~/Images/Competition/Badges/Gas_Savings/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 5, 80, 650, '~/Images/Competition/Badges/Gas_Savings/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 6, 100, 800, '~/Images/Competition/Badges/Gas_Savings/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 7, 200, 1050, '~/Images/Competition/Badges/Gas_Savings/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 8, 400, 1200, '~/Images/Competition/Badges/Gas_Savings/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 0, 0, 0, '~/Images/Competition/Badges/Challenges_Completed/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 1, 1, 50, '~/Images/Competition/Badges/Challenges_Completed/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 2, 5, 100, '~/Images/Competition/Badges/Challenges_Completed/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 3, 15, 250, '~/Images/Competition/Badges/Challenges_Completed/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 4, 30, 400, '~/Images/Competition/Badges/Challenges_Completed/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 5, 45, 650, '~/Images/Competition/Badges/Challenges_Completed/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 6, 65, 800, '~/Images/Competition/Badges/Challenges_Completed/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 7, 90, 1050, '~/Images/Competition/Badges/Challenges_Completed/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 8, 120, 1200, '~/Images/Competition/Badges/Challenges_Completed/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 9, -1, 0, '')

