insert into ActivEarth_Dev.dbo.users Values ('jtest', 'test123')
insert into ActivEarth_Dev.dbo.profile Values (1, 'John', 'Test', 'jtest@gmail.com', 'M', 'Derpville', 'VA', 21, 72, 175, 0, 0, 0, 0, 0)

insert into ActivEarth_Dev.dbo.users Values ('badgetest1', 'password')
insert into ActivEarth_Dev.dbo.profile Values (2, 'Test', 'Subject1', 'thisisatestaccount@email.com', 'M', 'Denver', 'CO', 21, 72, 175, 0, 0, 0, 0, 0)

insert into ActivEarth_Dev.dbo.users Values ('badgetest2', 'password2')
insert into ActivEarth_Dev.dbo.profile Values (3, 'Test', 'Subject2', 'anothertestaccount@email.com', 'M', 'St. Louis', 'MO', 26, 72, 175, 0, 0, 0, 0, 0)

insert into ActivEarth_Dev.dbo.users Values ('mark', 'k')
insert into ActivEarth_Dev.dbo.profile Values (4, 'Mark', 'Talley', 'yetanothertestaccount@email.com', 'M', 'Topeka', 'KS', 22, 71, 155, 0, 0, 0, 0, 0)

/* Statistic-based data (names, etc.) */
insert into ActivEarth_Dev.dbo.statistic_info Values (0, 'Steps', 'N0')
insert into ActivEarth_Dev.dbo.statistic_info Values (1, 'Distance Walked', 'N1')
insert into ActivEarth_Dev.dbo.statistic_info Values (2, 'Distance Biked', 'N1')
insert into ActivEarth_Dev.dbo.statistic_info Values (3, 'Distance Ran', 'N1')
insert into ActivEarth_Dev.dbo.statistic_info Values (4, 'Gas Money Saved', 'C')
insert into ActivEarth_Dev.dbo.statistic_info Values (5, 'Challenges Completed', 'N0')
insert into ActivEarth_Dev.dbo.statistic_info Values (6, 'Total Distance', 'N1')
insert into ActivEarth_Dev.dbo.statistic_info Values (7, 'Total Time', 'N2')
insert into ActivEarth_Dev.dbo.statistic_info Values (8, 'Time Walking', 'N2')
insert into ActivEarth_Dev.dbo.statistic_info Values (9, 'Time Biking', 'N2')
insert into ActivEarth_Dev.dbo.statistic_info Values (10, 'Time Running', 'N2')

/* Badge requirement information */
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 0, 0, 0, '~/Images/Competition/Badges/Steps/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 1, 30000, 50, '~/Images/Competition/Badges/Steps/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 2, 300000, 100, '~/Images/Competition/Badges/Steps/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 3, 900000, 250, '~/Images/Competition/Badges/Steps/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 4, 1800000, 400, '~/Images/Competition/Badges/Steps/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 5, 2850000, 650, '~/Images/Competition/Badges/Steps/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 6, 4050000, 800, '~/Images/Competition/Badges/Steps/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 7, 5550000, 1050, '~/Images/Competition/Badges/Steps/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 8, 7200000, 1200, '~/Images/Competition/Badges/Steps/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (0, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 0, 0, 0, '~/Images/Competition/Badges/Distance_Walked/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 1, 20, 50, '~/Images/Competition/Badges/Distance_Walked/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 2, 150, 100, '~/Images/Competition/Badges/Distance_Walked/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 3, 450, 250, '~/Images/Competition/Badges/Distance_Walked/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 4, 900, 400, '~/Images/Competition/Badges/Distance_Walked/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 5, 1425, 650, '~/Images/Competition/Badges/Distance_Walked/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 6, 2025, 800, '~/Images/Competition/Badges/Distance_Walked/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 7, 2775, 1050, '~/Images/Competition/Badges/Distance_Walked/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 8, 3600, 1200, '~/Images/Competition/Badges/Distance_Walked/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (1, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 0, 0, 0, '~/Images/Competition/Badges/Distance_Biked/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 1, 20, 50, '~/Images/Competition/Badges/Distance_Biked/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 2, 150, 100, '~/Images/Competition/Badges/Distance_Biked/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 3, 450, 250, '~/Images/Competition/Badges/Distance_Biked/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 4, 900, 400, '~/Images/Competition/Badges/Distance_Biked/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 5, 1425, 650, '~/Images/Competition/Badges/Distance_Biked/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 6, 2025, 800, '~/Images/Competition/Badges/Distance_Biked/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 7, 2775, 1050, '~/Images/Competition/Badges/Distance_Biked/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 8, 3600, 1200, '~/Images/Competition/Badges/Distance_Biked/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (2, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 0, 0, 0, '~/Images/Competition/Badges/Distance_Ran/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 1, 20, 50, '~/Images/Competition/Badges/Distance_Ran/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 2, 150, 100, '~/Images/Competition/Badges/Distance_Ran/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 3, 450, 250, '~/Images/Competition/Badges/Distance_Ran/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 4, 900, 400, '~/Images/Competition/Badges/Distance_Ran/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 5, 1425, 650, '~/Images/Competition/Badges/Distance_Ran/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 6, 2025, 800, '~/Images/Competition/Badges/Distance_Ran/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 7, 2775, 1050, '~/Images/Competition/Badges/Distance_Ran/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 8, 3600, 1200, '~/Images/Competition/Badges/Distance_Ran/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (3, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 0, 0, 0, '~/Images/Competition/Badges/Gas_Savings/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 1, 10, 50, '~/Images/Competition/Badges/Gas_Savings/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 2, 20, 100, '~/Images/Competition/Badges/Gas_Savings/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 3, 40, 250, '~/Images/Competition/Badges/Gas_Savings/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 4, 60, 400, '~/Images/Competition/Badges/Gas_Savings/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 5, 80, 650, '~/Images/Competition/Badges/Gas_Savings/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 6, 100, 800, '~/Images/Competition/Badges/Gas_Savings/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 7, 200, 1050, '~/Images/Competition/Badges/Gas_Savings/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 8, 400, 1200, '~/Images/Competition/Badges/Gas_Savings/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (4, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 0, 0, 0, '~/Images/Competition/Badges/Challenges_Completed/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 1, 1, 50, '~/Images/Competition/Badges/Challenges_Completed/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 2, 5, 100, '~/Images/Competition/Badges/Challenges_Completed/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 3, 15, 250, '~/Images/Competition/Badges/Challenges_Completed/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 4, 30, 400, '~/Images/Competition/Badges/Challenges_Completed/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 5, 45, 650, '~/Images/Competition/Badges/Challenges_Completed/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 6, 65, 800, '~/Images/Competition/Badges/Challenges_Completed/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 7, 90, 1050, '~/Images/Competition/Badges/Challenges_Completed/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 8, 120, 1200, '~/Images/Competition/Badges/Challenges_Completed/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (5, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 0, 0, 0, '~/Images/Competition/Badges/Total_Distance/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 1, 60, 50, '~/Images/Competition/Badges/Total_Distance/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 2, 450, 100, '~/Images/Competition/Badges/Total_Distance/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 3, 1350, 250, '~/Images/Competition/Badges/Total_Distance/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 4, 2700, 400, '~/Images/Competition/Badges/Total_Distance/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 5, 4275, 650, '~/Images/Competition/Badges/Total_Distance/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 6, 6075, 800, '~/Images/Competition/Badges/Total_Distance/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 7, 8325, 1050, '~/Images/Competition/Badges/Total_Distance/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 8, 10800, 1200, '~/Images/Competition/Badges/Total_Distance/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (6, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 0, 0, 0, '~/Images/Competition/Badges/Total_Time/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 1, 6, 50, '~/Images/Competition/Badges/Total_Time/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 2, 30, 100, '~/Images/Competition/Badges/Total_Time/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 3, 72, 250, '~/Images/Competition/Badges/Total_Time/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 4, 144, 400, '~/Images/Competition/Badges/Total_Time/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 5, 240, 650, '~/Images/Competition/Badges/Total_Time/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 6, 360, 800, '~/Images/Competition/Badges/Total_Time/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 7, 540, 1050, '~/Images/Competition/Badges/Total_Time/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 8, 750, 1200, '~/Images/Competition/Badges/Total_Time/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (7, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 0, 0, 0, '~/Images/Competition/Badges/Time_Walked/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 1, 2, 50, '~/Images/Competition/Badges/Time_Walked/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 2, 10, 100, '~/Images/Competition/Badges/Time_Walked/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 3, 24, 250, '~/Images/Competition/Badges/Time_Walked/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 4, 48, 400, '~/Images/Competition/Badges/Time_Walked/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 5, 80, 650, '~/Images/Competition/Badges/Time_Walked/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 6, 120, 800, '~/Images/Competition/Badges/Time_Walked/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 7, 180, 1050, '~/Images/Competition/Badges/Time_Walked/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 8, 250, 1200, '~/Images/Competition/Badges/Time_Walked/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (8, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 0, 0, 0, '~/Images/Competition/Badges/Time_Biked/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 1, 2, 50, '~/Images/Competition/Badges/Time_Biked/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 2, 10, 100, '~/Images/Competition/Badges/Time_Biked/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 3, 24, 250, '~/Images/Competition/Badges/Time_Biked/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 4, 48, 400, '~/Images/Competition/Badges/Time_Biked/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 5, 80, 650, '~/Images/Competition/Badges/Time_Biked/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 6, 120, 800, '~/Images/Competition/Badges/Time_Biked/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 7, 180, 1050, '~/Images/Competition/Badges/Time_Biked/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 8, 250, 1200, '~/Images/Competition/Badges/Time_Biked/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (9, 9, -1, 0, '')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 0, 0, 0, '~/Images/Competition/Badges/Time_Ran/None.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 1, 2, 50, '~/Images/Competition/Badges/Time_Ran/Bronze.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 2, 10, 100, '~/Images/Competition/Badges/Time_Ran/Silver.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 3, 24, 250, '~/Images/Competition/Badges/Time_Ran/Gold.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 4, 48, 400, '~/Images/Competition/Badges/Time_Ran/Platinum.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 5, 80, 650, '~/Images/Competition/Badges/Time_Ran/Ruby.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 6, 120, 800, '~/Images/Competition/Badges/Time_Ran/Sapphire.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 7, 180, 1050, '~/Images/Competition/Badges/Time_Ran/Emerald.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 8, 250, 1200, '~/Images/Competition/Badges/Time_Ran/Diamond.png')
insert into ActivEarth_Dev.dbo.badge_level_info Values (10, 9, -1, 0, '')

/* Available Challenges for Generator */
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 0, 10000, 5, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 0, 12000, 5, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 0, 14000, 10, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 0, 15000, 10, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 0, 20000, 15, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 0, 70000, 20, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 0, 80000, 20, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 0, 90000, 25, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 0, 100000, 25, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 0, 120000, 30, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 0, 280000, 40, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 0, 300000, 40, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 0, 320000, 45, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 0, 350000, 45, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 0, 400000, 50, 'Take {0} Steps.', '~/Images/Competition/Challenges/Steps/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 1, 3, 5, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 1, 5, 5, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 1, 7, 10, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 1, 8, 10, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 1, 10, 15, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 1, 15, 20, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 1, 20, 20, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 1, 30, 25, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 1, 40, 25, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 1, 50, 30, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 1, 85, 40, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 1, 95, 40, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 1, 110, 45, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 1, 125, 45, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 1, 150, 50, 'Walk {0} miles.', '~/Images/Competition/Challenges/Distance_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 2, 10, 5, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 2, 15, 5, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 2, 20, 10, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 2, 25, 10, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 2, 30, 15, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 2, 50, 20, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 2, 75, 20, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 2, 100, 25, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 2, 125, 25, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 2, 150, 30, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 2, 200, 40, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 2, 250, 40, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 2, 300, 45, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 2, 350, 45, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 2, 400, 50, 'Bike {0} miles.', '~/Images/Competition/Challenges/Distance_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 3, 3, 5, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 3, 5, 5, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 3, 7, 10, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 3, 8, 10, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 3, 10, 15, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 3, 15, 20, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 3, 20, 20, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 3, 30, 25, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 3, 40, 25, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 3, 50, 30, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 3, 100, 40, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 3, 125, 40, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 3, 150, 45, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 3, 175, 45, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 3, 200, 50, 'Run {0} miles.', '~/Images/Competition/Challenges/Distance_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 4, 0.5, 5, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 4, 1, 5, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 4, 1.5, 10, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 4, 2, 10, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 4, 2.5, 15, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 4, 3, 20, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 4, 6, 20, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 4, 9, 25, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 4, 12, 25, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 4, 15, 30, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 4, 12, 40, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 4, 24, 40, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 4, 36, 45, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 4, 48, 45, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 4, 60, 50, 'Save {0} in Gas Money through the use of Active Transportation.', '~/Images/Competition/Challenges/Gas_Savings/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 6, 7, 5, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 6, 10, 5, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 6, 13, 10, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 6, 16, 10, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 6, 19, 15, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 6, 49, 20, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 6, 70, 20, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 6, 91, 25, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 6, 112, 25, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 6, 133, 30, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 6, 196, 40, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 6, 280, 40, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 6, 364, 45, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 6, 448, 45, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 6, 532, 50, 'Travel a distance of {0} miles by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Distance/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 7, 1, 5, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 7, 1.5, 5, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 7, 2, 10, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 7, 2.5, 10, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 7, 3, 15, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 7, 4, 20, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 7, 6, 20, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 7, 8, 25, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 7, 10, 25, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 7, 12, 30, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 7, 16, 40, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 7, 24, 40, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 7, 32, 45, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 7, 40, 45, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 7, 48, 50, 'Accumulate {0} hours of active transportation by walking, running, and biking.', '~/Images/Competition/Challenges/Total_Time/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 8, 0.5, 5, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 8, 1, 5, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 8, 1.5, 10, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 8, 2, 10, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 8, 2.5, 15, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 8, 2.5, 20, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 8, 7, 20, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 8, 10.5, 25, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 8, 14, 25, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 8, 17.5, 30, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 8, 14, 40, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 8, 28, 40, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 8, 42, 45, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 8, 56, 45, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 8, 70, 50, 'Walk for {0} hours.', '~/Images/Competition/Challenges/Time_Walked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 9, 1, 5, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 9, 1.5, 5, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 9, 2, 10, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 9, 2.5, 10, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 9, 3, 15, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 9, 4, 20, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 9, 6, 20, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 9, 8, 25, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 9, 10, 25, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 9, 12, 30, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 9, 16, 40, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 9, 24, 40, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 9, 32, 45, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 9, 40, 45, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 9, 48, 50, 'Bike for {0} hours.', '~/Images/Competition/Challenges/Time_Biked/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 10, 0.25, 5, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 10, 0.5, 5, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 10, 0.75, 10, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 10, 1, 10, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 0, 10, 1.5, 15, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Daily.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 10, 1.75, 20, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 10, 3.5, 20, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 10, 5.25, 25, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 10, 7, 25, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (1, 0, 10, 10.5, 30, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Weekly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 10, 7, 40, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 10, 14, 40, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 10, 21, 45, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 10, 28, 45, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (2, 0, 10, 42, 50, 'Run for {0} hours.', '~/Images/Competition/Challenges/Time_Ran/Monthly.png', null)
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 1, 3, 13.1, 30, 'Run {0} miles in a single day.', '', 'Half-Marathon')
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 1, 3, 26.2, 60, 'Run {0} miles in a single day.', '', 'Marathon')
insert into ActivEarth_Dev.dbo.challenge_definitions Values (0, 1, 3, 31.1, 75, 'Run {0} miles in a single day.', '', 'Ultra-Marathon')

/* Test Contests */
insert into ActivEarth_Dev.dbo.contests Values ('Super Awesome Happy Funtime Contest', 'Description for Super Awesome Happy Funtime Contest', 500, 1, null, 9001, CURRENT_TIMESTAMP, 0, 0, 1, 1, null, 1)
insert into ActivEarth_Dev.dbo.contests Values ('Space Eyes', 'Description for Space Eyes', 500, 1, null, 9001, CURRENT_TIMESTAMP, 0, 0, 1, 1, null, 1)
insert into ActivEarth_Dev.dbo.contests Values ('No I Needed That.', 'Description for No I needed that.', 500, 1, null, 9001, CURRENT_TIMESTAMP, 0, 0, 1, 1, null, 1)
insert into ActivEarth_Dev.dbo.contests Values ('The Doctor', 'Description for The Doctor', 500, 1, null, 9001, CURRENT_TIMESTAMP, 0, 1, 1, 1, null, 1)

/* Teams for Super Awesome Happy Funtime Contest */
insert into ActivEarth_Dev.dbo.teams Values (1, 'SAHFC Team 1', 0, 0, 0, null)
insert into ActivEarth_Dev.dbo.teams Values (1, 'SAHFC Team 2', 0, 0, 0, null)

/* Teams for Space Eyes Contest */
insert into ActivEarth_Dev.dbo.teams Values (2, 'Space Eyes Team 1', 0, 0, 0, null)
insert into ActivEarth_Dev.dbo.teams Values (2, 'Space Eyes Team 2', 0, 0, 0, null)

/* Teams for No I Needed That Contest */
insert into ActivEarth_Dev.dbo.teams Values (3, 'NINT Team 1', 0, 0, 0, null)
insert into ActivEarth_Dev.dbo.teams Values (3, 'NINT Team 2', 0, 0, 0, null)
insert into ActivEarth_Dev.dbo.teams Values (3, 'NINT Team 3', 0, 0, 0, null)

/* Teams for The Doctor Contest */
insert into ActivEarth_Dev.dbo.teams Values (4, 'John Test', 0, 0, 0, null)
insert into ActivEarth_Dev.dbo.teams Values (4, 'Test Subject1', 0, 0, 0, null)
insert into ActivEarth_Dev.dbo.teams Values (4, 'Test Subject2', 0, 0, 0, null)
insert into ActivEarth_Dev.dbo.teams Values (4, 'Mark Talley', 0, 0, 0, null)

/* Team members for SAHFC */
insert into ActivEarth_Dev.dbo.team_members Values (1, 1, 1, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (1, 1, 2, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (1, 2, 3, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (1, 2, 4, 0, 0)

/* Team members for SEC */
insert into ActivEarth_Dev.dbo.team_members Values (2, 3, 1, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (2, 3, 2, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (2, 4, 3, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (2, 4, 4, 0, 0)

/* Team members for NINTC */
insert into ActivEarth_Dev.dbo.team_members Values (3, 5, 1, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (3, 5, 2, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (3, 6, 3, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (3, 7, 4, 0, 0)

/* Team members for TDC */
insert into ActivEarth_Dev.dbo.team_members Values (4, 8, 1, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (4, 9, 2, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (4, 10, 3, 0, 0)
insert into ActivEarth_Dev.dbo.team_members Values (4, 11, 4, 0, 0)