//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivEarth.Competition.Challenges {
    
    
    public partial class DisplayChallengesPage {
        
        /// <summary>
        /// _displayDailyChallenges control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActivEarth.Competition.Challenges.DisplayChallengesControl _displayDailyChallenges;
        
        /// <summary>
        /// _displayWeeklyChallenges control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActivEarth.Competition.Challenges.DisplayChallengesControl _displayWeeklyChallenges;
        
        /// <summary>
        /// _displayMonthlyChallenges control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActivEarth.Competition.Challenges.DisplayChallengesControl _displayMonthlyChallenges;
        
        /// <summary>
        /// _displayPersistentChallenges control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActivEarth.Competition.Challenges.DisplayChallengesControl _displayPersistentChallenges;
    }
}
